stages:

  - scc
  - oss
  - genLicense

scc:
  stage: scc
  tags:
  - LINUX 
  script:
    - echo "Enter scc stage"
    - scc | tee scc.txt
    - bash /usr/bin/scc_calc.sh
    - echo "The End SCC result:"
    - cat scc.txt
  artifacts:
    paths:
    - scc.txt
  when: manual

oss:
  tags:
    - OSS
  stage: oss
  dependencies: []
  script:
    - oss_checking .
  artifacts:
    paths:
    - scan_result
  when: manual

genLicense:
  variables:
    CODE_COMPILE_ARCH: 'EAGLE_ANDES'
    COV_PF_CATALOG: 'BLE'
  stage: genLicense
  tags:
  - LINUX 
  before_script:
  script:
    - date
    - generat_license_list
    - date
  artifacts:
    paths:
    - "license_list_gen.txt"
    - "no_license_list_gen.txt"
    - "mismatch_license_file_gen.txt"
  when: manual



